[project]
name = "auto-cast-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ruff>=0.14.5",
    "customtkinter>=5.2.2",
    "pyinstaller>=6.12.0",
    "pystray>=0.19.5",
    "pillow>=10.0.0",
]
